# TODO: find a way to change localhost to something else in remote env
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: $OTEL_HOSTNAME$:4317

exporters:
  otlp/jaeger:
    endpoint: $OTEL_HOSTNAME$:4317
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/jaeger