# Use RHEL UBI9 Minimal base
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

USER root
RUN microdnf install -y tar gzip shadow-utils time zip unzip findutils which && microdnf clean all

# Accept build-time argument with a default fallback
ARG JAVA_VERSION="25.0.1-tem"
ENV JAVA_VERSION=${JAVA_VERSION}
ENV SDKMAN_DIR="/root/.sdkman"

# Install SDKMAN and Java
RUN curl -s "https://get.sdkman.io" | bash && \
    bash -c "source $SDKMAN_DIR/bin/sdkman-init.sh && \
    sdk install java $JAVA_VERSION && \
    sdk default java $JAVA_VERSION"

ENV JAVA_HOME="${SDKMAN_DIR}/candidates/java/current"
ENV PATH="${JAVA_HOME}/bin:${PATH}"
